### ISSUE TITLE
library to load: DlOpen { desc: "../Neotron-OS/target/debug/libneotron_os.so: undefined symbol: rust_eh_personality" }

### ISSUE THREAD

**Issue by CHiPs44** [Neotron-Compute/Neotron-OS#77]
I'm trying to run last Neotron-OS, and I'm a complete beginner with Rust:

```bash
~/src/Neotron-Desktop-BIOS$ export RUST_BACKTRACE=full
~/src/Neotron-Desktop-BIOS$ ./target/release/neotron-desktop-bios --os ../Neotron-OS/target/debug/libneotron_os.so --disk disk.img.gz --nvram NVRAM
thread 'main' panicked at src/main.rs:736:58:
library to load: DlOpen { desc: "../Neotron-OS/target/debug/libneotron_os.so: undefined symbol: rust_eh_personality" }
stack backtrace:
   0:     0x558fe2e4044c - std::backtrace_rs::backtrace::libunwind::trace::he43a6a3949163f8c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x558fe2e4044c - std::backtrace_rs::backtrace::trace_unsynchronized::h50db52ca99f692e7
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x558fe2e4044c - std::sys_common::backtrace::_print_fmt::hd37d595f2ceb2d3c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x558fe2e4044c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h678bbcf9da6d7d75
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x558fe2e6730c - core::fmt::rt::Argument::fmt::h3a159adc080a6fc9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/rt.rs:138:9
   5:     0x558fe2e6730c - core::fmt::write::hb8eaf5a8e45a738e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/fmt/mod.rs:1094:21
   6:     0x558fe2e3dc6e - std::io::Write::write_fmt::h9663fe36b2ee08f9
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/io/mod.rs:1714:15
   7:     0x558fe2e40234 - std::sys_common::backtrace::_print::hcd4834796ee88ad2
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:47:5
   8:     0x558fe2e40234 - std::sys_common::backtrace::print::h1360e9450e4f922a
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:34:9
   9:     0x558fe2e418e3 - std::panicking::default_hook::{{closure}}::h2609fa95cd5ab1f4
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:270:22
  10:     0x558fe2e415fc - std::panicking::default_hook::h6d75f5747cab6e8d
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:290:9
  11:     0x558fe2e41e69 - std::panicking::rust_panic_with_hook::h57e78470c47c84de
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:707:13
  12:     0x558fe2e41d67 - std::panicking::begin_panic_handler::{{closure}}::h3dfd2453cf356ecb
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:599:13
  13:     0x558fe2e40976 - std::sys_common::backtrace::__rust_end_short_backtrace::hdb177d43678e4d7e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/sys_common/backtrace.rs:170:18
  14:     0x558fe2e41ab2 - rust_begin_unwind
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:595:5
  15:     0x558fe2cd85d3 - core::panicking::panic_fmt::hd1e971d8d7c78e0e
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/panicking.rs:67:14
  16:     0x558fe2cd89da - core::result::unwrap_failed::hccb456d39e9c31fc
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/result.rs:1652:5
  17:     0x558fe2cdbc9b - neotron_desktop_bios::main::hccf6d6e64118dde4
  18:     0x558fe2cf4863 - std::sys_common::backtrace::__rust_begin_short_backtrace::hab7f4d5ae365304a
  19:     0x558fe2ced0a9 - std::rt::lang_start::{{closure}}::h554f69aca5a9f559
  20:     0x558fe2e386db - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hbcc4f8a3f5ada78c
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/core/src/ops/function.rs:284:13
  21:     0x558fe2e386db - std::panicking::try::do_call::he5f117a9e13dadde
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  22:     0x558fe2e386db - std::panicking::try::h2f3af9afce3a0443
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  23:     0x558fe2e386db - std::panic::catch_unwind::h6d6c387f38ef05ea
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  24:     0x558fe2e386db - std::rt::lang_start_internal::{{closure}}::h6ca09d5905711415
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:48
  25:     0x558fe2e386db - std::panicking::try::do_call::ha9fd18ea06654a4b
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:502:40
  26:     0x558fe2e386db - std::panicking::try::hda5c2a4432362341
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panicking.rs:466:19
  27:     0x558fe2e386db - std::panic::catch_unwind::h440f731b142bc235
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/panic.rs:142:14
  28:     0x558fe2e386db - std::rt::lang_start_internal::hc0b4e50f058f62ce
                               at /rustc/cc66ad468955717ab92600c770da8c1601a4ff33/library/std/src/rt.rs:148:20
  29:     0x558fe2ce1c35 - main
  30:     0x7f87f5829d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  31:     0x7f87f5829e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  32:     0x558fe2cd8c55 - _start
  33:                0x0 - <unknown>
```

Compilation of Neotron-OS seemed to be fine:

```bash
~/src/Neotron-OS$ cargo build --lib
   Compiling autocfg v1.1.0
   Compiling semver v1.0.18
   Compiling proc-macro2 v1.0.66
   Compiling scopeguard v1.2.0
   Compiling unicode-ident v1.0.11
   Compiling byteorder v1.4.3
   Compiling serde v1.0.174
   Compiling lock_api v0.4.10
   Compiling num-traits v0.2.16
   Compiling rustc_version v0.4.0
   Compiling serde_derive v1.0.174
   Compiling nb v1.1.0
   Compiling nb v0.1.3
   Compiling heapless v0.7.16
   Compiling spin v0.9.8
   Compiling quote v1.0.31
   Compiling hash32 v0.2.1
   Compiling neotron-ffi v0.1.0
   Compiling stable_deref_trait v1.2.0
   Compiling void v1.0.2
   Compiling vte_generate_state_changes v0.1.1
   Compiling embedded-hal v0.2.7
   Compiling bitflags v2.3.3
   Compiling pc-keyboard v0.7.0
   Compiling chrono v0.4.26
   Compiling neotron-os v0.6.0 (/home/chips/src/Neotron-OS)
   Compiling cobs v0.2.3
   Compiling arrayvec v0.7.4
   Compiling utf8parse v0.2.1
   Compiling vte v0.12.0
   Compiling neotron-api v0.1.0
   Compiling neotron-common-bios v0.11.1
   Compiling embedded-sdmmc v0.5.0
   Compiling r0 v1.0.0
   Compiling menu v0.3.2
   Compiling neotron-loader v0.1.0
   Compiling postcard v1.0.6
    Finished dev [unoptimized + debuginfo] target(s) in 9.04s
```

Rust info on my Ubuntu 22.04 machine:

```bash
~/src/Neotron-Desktop-BIOS$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/chips/snap/rustup/common/rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.73.0 (cc66ad468 2023-10-03)
```

**Comment by CHiPs44** [comment]
My bad, I should have opened this issue in <https://github.com/Neotron-Compute/Neotron-Desktop-BIOS/issues>!

**Comment by CHiPs44** [comment]
Done, see <https://github.com/Neotron-Compute/Neotron-Desktop-BIOS/issues/13>
